on: [push]

jobs:
  table:
    runs-on: ubuntu-latest
    name: Update README from json data
    steps:
    - uses: actions/checkout@v2
    - name: Read/Write data into README
      uses: eddiejaoude/github-actions-reader-writer@v0.1.1
      with:
        json-file-path: 'data.json'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        columns: 1
        object-field-names: '[ "number", "projectName", "url" ]'
        html-cell: '<td align="center"><a href="{{ url }}">{{ number }}.{{ projectName }}</a> </td>'  
